config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: [:index, :show, :create]
  resources :friendships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships
  has_many :friends, through: :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  after_create :create_short_url
  after_create :get_topics

  def all_friendships
    (self.friends + self.inverse_friends).uniq
  end

  def connection(user)
    if user.all_friendships.include?(self)
      " is already your friend."
    else
      degrees_of_separation(user)
    end
  end

  #refactor to remove 2 if/else statements to return nil 
  def degrees_of_separation(user)
    friends = user.all_friendships & self.all_friendships
    if friends.present?
      "#{friends.map(&:name).join(', or ')} knows "
    else
       "There are no friends with 2 degrees of separation with "
    end
  end

  private

  def create_short_url
    Users::Shorten.get_short_url(user: self)
  end

  def get_topics
    Users::Info.get_topics(user: self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    if @user.friendships.exists?(friend_id: params[:friend_id])
      format.html { redirect_to user_path(@user), notice: 'They are already friends.' }
    else
      @user.friendships.build(friend_id: params[:friend_id])


    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(@user), notice: 'Friendship was successfully added.' }
      else
        format.html { render :new }
        format.json { redirect_to root_url, alert: 'Friendship was not added.' }
      end
    end
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    friend = @user.friendships.where(friend_id: params[:friend_id])
    if friend
      @user.friendships.delete(friend)
    end

    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'Friendship was deleted.' }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @friends = @user.all_friendships.delete(@user)
    @people = User.all - @user.all_friendships

    if params[:search]
      @users = User.where("topics Ilike ?", "%#{params[:search]}%")
    else
      @users = []
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :website_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ever</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<section>

<h1>Expert List</h1>

<h4>Add a new user</h4>
<%= form_for @user do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :website_url %>
  <%= f.submit "Create" %>
<% end %>

<% @users.each do |u| %>
  <p>
    <h4><%= link_to u.name, user_path(u) %>:</h4>
  </p>
<% end %>


</section>

app/views/users/show.html.erb
<div>back to: <%= link_to "Expert List", users_path %></div>

<br />

<div>
  <h2>Name: <%= @user.name %></h2>
  <h3>Website: <%= @user.website_url %></h3>
  <h3>Short Url: <%= @user.short_url %></h3>
  <h3>topics: </h3> <div><%= @user.topics %></div>
</div>

<br />

<div>
  <h4>Search for an Expert by Topic</h4>
  <%= form_tag user_path, method: "get" do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Topics" %>
    <%= submit_tag "Search", name: nil %>
  <% end %>

  <% @users.each do |user| %>
    <p><%= @user.connection(user) %> <%= link_to user.name, user_path(user) %>.
  <% end %>
</div>

<div>
  <% if @user.friends.present?%>
    <h4><%= @user.name %>'s Friends</h4>
    <ul>
      <% @user.friends.each do |friendship| %>
        <li>
          <%= link_to friendship.name, user_path(friendship.id) %>
          (<%= link_to "Remove Friend", friendship_path(user_id: @user.id, friend_id: friendship.id), method: :delete %>)
        </li>
      <% end %>
    </ul>
  <% end %>
<!-- add inverse friends to this loop  -->
  <!-- <% if @user.inverse_friends.present? %>
    <ul>
      <% @user.inverse_friends.each do |friendship| %>
        <li>
          <%= link_to friendship.name, user_path(friendship.id) %>
          (<%= link_to "Remove Friend", friendship_path(user_id: @user.id, friend_id: friendship.id), method: :delete %>)
        </li>
      <% end %>
    </ul>
  <% end %> -->
</div>

<hr />
<div>
<h4>Not Friends With:</h4>
  <% @people.each do |person| %>
    <p>
      <%= link_to person.name, user_path(person) %> (<%= link_to "Add Friend", friendships_path(friend_id: person, user_id: @user.id), method: :post %>)
    </p>
  <% end %>
</div>